name: CI
on: [push, workflow_dispatch]
jobs:
  build:
    name: "build svgomg"
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    steps:
    - 
      name: "checkout repo"
      uses: actions/checkout@master
    - 
      name: "setup node v16"
      uses: actions/setup-node@master
      with:
        node-version: 16
    - 
      name: "(env) pnpm"
      run: curl -L https://pnpm.js.org/pnpm.js | node - add --global pnpm
    - 
      name: "(env) cache"
      uses: actions/cache@master
      with:
        path: ~/.pnpm-store
        key: ${{ runner.os }}-${{ matrix.nodejs }}-${{ hashFiles('**/package.json') }}
        restore-keys: ${{ runner.os }}-${{ matrix.nodejs }}-
    - 
      name: "install dependencies"
      run: pnpm install
    - 
      name: "build svgomg"
      run: pnpm run build
    - 
      name: "upload artifact"
      uses: actions/upload-artifact@master
      if: github.repository == 'flourd/svgo'
      with:
        name: build
        path: ./build/
        if-no-files-found: error

  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    if: github.repository == 'flourd/svgo'
    steps:
      - 
        name: "checkout repo"
        uses: actions/checkout@master
      - 
        name: "download artifacts"
        uses: actions/download-artifact@master
        with:
          name: build
          path: ./build/
      -
        name: "(env) setup gpg"
        uses: crazy-max/ghaction-import-gpg@v3
        with:
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}
          git-user-signingkey: true
          git-config-global: true
          git-commit-gpgsign: true
          git-tag-gpgsign: true
      - 
        if: success()
        name: "🚀 deploy"
        uses: crazy-max/ghaction-github-pages@v2.6.0
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        with:
          author: "Nicholas Berlette <nick@berlette.com>"
          committer: "Nicholas Berlette <nick@berlette.com>"
          commit_message: "🚀"
          target_branch: gh-pages
          build_dir: build
          fqdn: svgo.tk
          keep_history: true
          dry_run: false
          verbose: true
          jekyll: false
